### ISSUE TITLE
Problem with new comments

### ISSUE THREAD

**Issue by ghost** [ThomDietrich/jcomments#1]
Hi,
Did you still working on this project? I have small problem with recaptcha 2.0 and post new comments in real time. When recaptcha is turn on, after send new comment, for a short time appears over and over again and nothing happens. You can not see new comment does not appear thanks for your comment. Only refreshing the whole page then appears comment.
BR
Bartosz

**Comment by ThomDietrich** [comment]
Hey, I am still using the modifications and the plugin does a good enough job for me. I was hoping, the jcomments guys would release a more complete and tested version of jcomments with recaptcha 2.0.
I don't really have the time to work on fixes right now but if you are able to fix the described behavior, please send me your modifications and I will include them for others to find. Thanks!
