### ISSUE TITLE
PostgreSQL support.

### ISSUE THREAD

**Issue by twister65** [ThomDietrich/jcomments#4]
PR #5 adds postgreSQL support.

**Comment by twister65** [comment]
I'm using it for my website:
http://avenirdurable.free.fr/index.php/definition
It works perfectly well with a postgreSQL database.

**Comment by twister65** [comment]
PR https://github.com/ThomDietrich/jcomments/pull/5 adds postgreSQL support.

**Comment by ThomDietrich** [comment]
Thanks! let's discuss it over there
